# Generated by Django 2.0.6 on 2018-06-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0004_auto_20180606_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateDue',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='owner',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
