# Generated by Django 2.0.6 on 2018-06-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0008_auto_20180610_0026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['dateCreated']},
        ),
        migrations.RemoveField(
            model_name='note',
            name='subject',
        ),
        migrations.AddField(
            model_name='note',
            name='group',
            field=models.CharField(blank=True, help_text='Assign the note to a group', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='colour',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow')], help_text='Colour code the note', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateDue',
            field=models.DateTimeField(blank=True, help_text='Set a reminder date', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, help_text='Any additional information', null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(help_text='Main description of your task', max_length=50),
        ),
    ]
