# Generated by Django 2.0.6 on 2018-06-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0009_auto_20180610_0056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateCreated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='note',
            name='dateDue',
            field=models.DateTimeField(blank=True, help_text='Set a reminder date', null=True, verbose_name='date due'),
        ),
    ]
