# Generated by Django 2.0.5 on 2018-06-01 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.IntegerField()),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('colours', models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=4)),
                ('subject', models.CharField(max_length=20)),
                ('dateCreated', models.DateTimeField(verbose_name='date created')),
                ('dateDue', models.DateTimeField(verbose_name='date due')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
