# Generated by Django 2.0.6 on 2018-06-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0002_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='colours',
            new_name='colour',
        ),
    ]
