# Generated by Django 2.0.5 on 2018-06-06 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0003_auto_20180605_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='colour',
            field=models.CharField(choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=20),
        ),
    ]
