# Generated by Django 2.0.6 on 2018-06-09 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0005_auto_20180609_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='dateDue',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
