# Generated by Django 2.0.6 on 2018-06-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesApp', '0006_auto_20180609_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='colour',
            field=models.CharField(blank=True, choices=[('blue', 'Blue'), ('red', 'Red'), ('green', 'Green'), ('yellow', 'Yellow')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='subject',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
